### ISSUE TITLE
Missing 'https' for maxcdn.bootstrapcdn.com in layout.html cause long load time

### ISSUE THREAD

**Issue by kmartinet-reference** [onefinestay/sphinx-nameko-theme#3]
The url for the maxcdn.bootstrapcdn.com style sheet does not have "https:" in front of it in the file "sphinx_nameko_theme/nameko/layout.html".
This cause long load time when trying to load a resulting web site locally with Chrome or Edge.

It seems that when the https is missing in front or the url, the browsers search locally for the url first, before appending the missing https and searching on the Internet.

Thank you and have a nice day,

Kevin

**Comment by mattbennett** [comment]
I don't actually have contributor writes to this repo anymore, but I have raised a pull request.

If anyone from onefinestay is able, it would be nice to transfer this repo to the official nameko org (along with nameko-sqlalchemy, which we also forgot to transfer).

cc @astronizzle @amitlalani
